import { StatusBar } from 'expo-status-bar';
import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, Text, View } from 'react-native';
import { api, Cart, Category, Order, Product, User, WishlistItem } from './src/api';
import { colors, styles } from './src/theme';
import { AuthScreen } from './src/screens/AuthScreen';
import { VerifyEmailScreen } from './src/screens/VerifyEmailScreen';
import { ShopScreen } from './src/screens/ShopScreen';
import { CartScreen } from './src/screens/CartScreen';
import { WishlistScreen } from './src/screens/WishlistScreen';
import { OrdersScreen } from './src/screens/OrdersScreen';
import { PaymentScreen } from './src/screens/PaymentScreen';
import { AccountScreen } from './src/screens/AccountScreen';

export type AppScreen = 'auth' | 'verify' | 'shop' | 'cart' | 'wishlist' | 'orders' | 'payment' | 'account';
type Tab = Exclude<AppScreen, 'auth' | 'verify' | 'payment'>;

export default function App() {
  const [screen, setScreen] = useState<AppScreen>('auth'), [message, setMessage] = useState('');
  const [token, setToken] = useState<string | null>(null), [refresh, setRefresh] = useState<string | null>(null), [user, setUser] = useState<User | null>(null);
  const [products, setProducts] = useState<Product[]>([]), [categories, setCategories] = useState<Category[]>([]), [cart, setCart] = useState<Cart | null>(null), [saved, setSaved] = useState<WishlistItem[]>([]), [orders, setOrders] = useState<Order[]>([]), [paymentOrder, setPaymentOrder] = useState<Order | null>(null), [selected, setSelected] = useState<Product | null>(null);
  const fail = (e: unknown) => setMessage(e instanceof Error ? e.message : String(e));
  const run = async (fn: () => Promise<void>) => { setMessage(''); try { await fn(); } catch (e) { fail(e); } };
  const loadUserData = async (t: string, u: User) => { const [c, w, o] = await Promise.all([api.cart(t, u.id), api.wishlist(t, u.id), api.orders(t, u.id)]); setCart(c); setSaved(w); setOrders(o); };
  const login = async (email: string, password: string) => { const auth = await api.login({ email, password }); const u = await api.me(auth.accessToken); setToken(auth.accessToken); setRefresh(auth.refreshToken); setUser(u); await loadUserData(auth.accessToken, u); setScreen('shop'); };
  const addToCart = (id: string) => run(async () => { if (token && user) { setCart(await api.addCart(token, user.id, id, 1)); setMessage('Added to your bag'); } });
  const toggleSaved = (id: string) => run(async () => { if (!token || !user) return; if (saved.some(i => i.productId === id)) { await api.removeWishlist(token, user.id, id); setSaved(saved.filter(i => i.productId !== id)); } else setSaved([...saved, await api.addWishlist(token, user.id, id)]); });
  useEffect(() => { if (token) Promise.all([api.products(token), api.categories(token)]).then(([p, c]) => { setProducts(p); setCategories(c); }).catch(fail); }, [token]);
  if (!token || !user) { if (screen === 'verify') return <VerifyEmailScreen email={message} onVerified={() => { setMessage('Email verified. You can now sign in.'); setScreen('auth'); }} message="" />; return <AuthScreen onLogin={login} onRegistered={email => { setMessage(email); setScreen('verify'); }} message={message} />; }
  const openPayment = (order: Order) => { setPaymentOrder(order); setScreen('payment'); };
  const content = screen === 'shop' ? <ShopScreen products={products} categories={categories} saved={saved} token={token} onAdd={addToCart} onSave={toggleSaved} onSelect={setSelected} /> : screen === 'cart' ? <CartScreen cart={cart} token={token} userId={user.id} onChange={setCart} onCheckout={() => run(async () => { const order = await api.checkout(token, user.id); setOrders([order, ...orders]); setCart({ customerId: user.id, items: [], cartSubtotal: 0 }); openPayment(order); })} /> : screen === 'wishlist' ? <WishlistScreen items={saved} onRemove={toggleSaved} /> : screen === 'orders' ? <OrdersScreen orders={orders} onPay={openPayment} /> : screen === 'payment' && paymentOrder ? <PaymentScreen order={paymentOrder} token={token} onBack={() => setScreen('orders')} onComplete={message => { setMessage(message); setOrders(orders.map(o => o.orderId === paymentOrder.orderId ? { ...o, status: 'PAID' } : o)); setScreen('orders'); }} /> : <AccountScreen user={user} refresh={refresh} onRefresh={() => run(async () => { if (refresh) { const auth = await api.refreshToken(refresh); setToken(auth.accessToken); setRefresh(auth.refreshToken); } })} onLogout={() => run(async () => { await api.logout(user.email); setToken(null); setUser(null); setScreen('auth'); })} onVerified={() => setScreen('verify')} />;
  return <SafeAreaView style={styles.safe}><StatusBar style="dark" />{screen !== 'payment' && <View style={{ paddingHorizontal: 22, paddingTop: 18, paddingBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><View><Text style={{ color: colors.gold, fontWeight: '700', fontSize: 11, letterSpacing: 2 }}>NOVA MARKET</Text><Text style={styles.title}>{screen === 'shop' ? 'Find your next favorite' : screen[0].toUpperCase() + screen.slice(1)}</Text></View><Pressable style={{ width: 40, height: 40, borderRadius: 20, backgroundColor: colors.sage, alignItems: 'center', justifyContent: 'center' }} onPress={() => setScreen('account')}><Text style={{ color: '#2b482e', fontWeight: '800', fontSize: 17 }}>{user.nickName?.[0]?.toUpperCase()}</Text></Pressable></View>}{message ? <Pressable onPress={() => setMessage('')}><Text style={styles.notice}>{message}</Text></Pressable> : null}<View style={styles.screen}>{selected ? <ProductPreview item={selected} onClose={() => setSelected(null)} onAdd={addToCart} /> : content}</View>{screen !== 'payment' && <Navigation current={screen as Tab} go={setScreen} cartCount={cart?.items.length || 0} />}</SafeAreaView>;
}
function ProductPreview({ item, onClose, onAdd }: { item: Product; onClose: () => void; onAdd: (id: string) => void }) { return <View style={{ padding: 22 }}><Pressable onPress={onClose}><Text style={{ color: colors.forest, fontWeight: '700' }}>Close</Text></Pressable><Text style={[styles.title, { marginTop: 25 }]}>{item.name}</Text><Text style={{ color: colors.gold, marginTop: 8 }}>{item.categoryName || 'CURATED PICK'}</Text><Text style={{ fontSize: 20, color: '#405742', fontWeight: '700', marginTop: 9 }}>{`₦${Number(item.price).toLocaleString()}`}</Text><Text style={{ color: colors.muted, lineHeight: 23, marginTop: 16 }}>{item.description || 'Thoughtfully selected for everyday living.'}</Text><Pressable style={styles.primary} onPress={() => { onAdd(item.id); onClose(); }}><Text style={styles.primaryText}>Add to bag</Text></Pressable></View>; }
function Navigation({ current, go, cartCount }: { current: Tab; go: (screen: AppScreen) => void; cartCount: number }) { const items: [Tab, string][] = [['shop', 'Discover'], ['cart', `Bag${cartCount ? ` (${cartCount})` : ''}`], ['wishlist', 'Saved'], ['orders', 'Orders'], ['account', 'Account']]; return <View style={{ flexDirection: 'row', borderTopWidth: 1, borderColor: colors.line, backgroundColor: colors.white, paddingTop: 9, paddingBottom: 5 }}>{items.map(([key, label]) => <Pressable style={{ flex: 1, alignItems: 'center' }} key={key} onPress={() => go(key)}><Text style={{ fontSize: 21, color: current === key ? colors.forest : '#a0a49b' }}>{key === 'shop' ? '⌂' : key === 'cart' ? '▱' : key === 'wishlist' ? '♡' : key === 'orders' ? '◷' : '○'}</Text><Text style={{ fontSize: 10, color: current === key ? colors.forest : '#8b8d84' }}>{label}</Text></Pressable>)}</View>; }
